### ISSUE TITLE
Getting "GeneralError" when executing actions.

### ISSUE THREAD

**Issue by minersunited** [phillipsnick/apc-pdu-snmp#19]
I am having an interesting issue turning some outlets off/on. I am attempting to control some APC PDU's, model #AP8965. When turning an outlet off or on I get the following error.

{ RequestFailedError: GeneralError: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.10
    at Object.Session.onSimpleGetResponse [as onResponse] (/path/to/relevant/directory/node_modules/net-snmp/index.js:946:16)
    at Session.onMsg (/path/to/relevant/directory/node_modules/net-snmp/index.js:920:9)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
  name: 'RequestFailedError',
  message: 'GeneralError: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.10',
  status: 5 }

The weird thing is that the actions ARE going through, the outlets are turning off and on as expected. Have you run into this in the past? Any chance you could point me in the right direction?

**Comment by minersunited** [comment]
Did not mean to post this twice!
